# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fbarden/Documents/ProjectManager/views/UI/ClauseView.ui'
#
# Created: Tue May 28 02:22:43 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_clauseViewWidget(object):
    def setupUi(self, clauseViewWidget):
        clauseViewWidget.setObjectName(_fromUtf8("clauseViewWidget"))
        clauseViewWidget.resize(1078, 713)
        self.verticalLayout_4 = QtGui.QVBoxLayout(clauseViewWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.previousButton = QtGui.QToolButton(clauseViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.previousButton.setObjectName(_fromUtf8("previousButton"))
        self.horizontalLayout.addWidget(self.previousButton)
        self.line_2 = QtGui.QFrame(clauseViewWidget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.returnButton = QtGui.QToolButton(clauseViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnButton.sizePolicy().hasHeightForWidth())
        self.returnButton.setSizePolicy(sizePolicy)
        self.returnButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.returnButton.setObjectName(_fromUtf8("returnButton"))
        self.horizontalLayout.addWidget(self.returnButton)
        self.titleLabel = QtGui.QLabel(clauseViewWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.horizontalLayout.addWidget(self.titleLabel)
        self.upButton = QtGui.QToolButton(clauseViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setMaximumSize(QtCore.QSize(50, 50))
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.horizontalLayout.addWidget(self.upButton)
        self.deleteButton = QtGui.QToolButton(clauseViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout.addWidget(self.deleteButton)
        self.line_3 = QtGui.QFrame(clauseViewWidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.nextButton = QtGui.QToolButton(clauseViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(clauseViewWidget)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.editTab = QtGui.QWidget()
        self.editTab.setObjectName(_fromUtf8("editTab"))
        self.widget = QtGui.QWidget(self.editTab)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.showUplinksCheckBox = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showUplinksCheckBox.sizePolicy().hasHeightForWidth())
        self.showUplinksCheckBox.setSizePolicy(sizePolicy)
        self.showUplinksCheckBox.setText(_fromUtf8(""))
        self.showUplinksCheckBox.setChecked(True)
        self.showUplinksCheckBox.setObjectName(_fromUtf8("showUplinksCheckBox"))
        self.horizontalLayout_2.addWidget(self.showUplinksCheckBox)
        self.uplinksLabel = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uplinksLabel.sizePolicy().hasHeightForWidth())
        self.uplinksLabel.setSizePolicy(sizePolicy)
        self.uplinksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.uplinksLabel.setObjectName(_fromUtf8("uplinksLabel"))
        self.horizontalLayout_2.addWidget(self.uplinksLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.uplinksTreeWidget = QtGui.QTreeWidget(self.widget)
        self.uplinksTreeWidget.setObjectName(_fromUtf8("uplinksTreeWidget"))
        self.uplinksTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.uplinksTreeWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fontComboBox = QtGui.QFontComboBox(self.widget)
        self.fontComboBox.setObjectName(_fromUtf8("fontComboBox"))
        self.horizontalLayout_4.addWidget(self.fontComboBox)
        self.fontSizeComboBox = QtGui.QComboBox(self.widget)
        self.fontSizeComboBox.setObjectName(_fromUtf8("fontSizeComboBox"))
        self.horizontalLayout_4.addWidget(self.fontSizeComboBox)
        self.boldButton = QtGui.QToolButton(self.widget)
        self.boldButton.setArrowType(QtCore.Qt.NoArrow)
        self.boldButton.setObjectName(_fromUtf8("boldButton"))
        self.horizontalLayout_4.addWidget(self.boldButton)
        self.italicButton = QtGui.QToolButton(self.widget)
        self.italicButton.setObjectName(_fromUtf8("italicButton"))
        self.horizontalLayout_4.addWidget(self.italicButton)
        self.underlineButton = QtGui.QToolButton(self.widget)
        self.underlineButton.setObjectName(_fromUtf8("underlineButton"))
        self.horizontalLayout_4.addWidget(self.underlineButton)
        self.imageButton = QtGui.QToolButton(self.widget)
        self.imageButton.setObjectName(_fromUtf8("imageButton"))
        self.horizontalLayout_4.addWidget(self.imageButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.textEdit = QtGui.QTextEdit(self.widget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.downlinksCheckBox = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downlinksCheckBox.sizePolicy().hasHeightForWidth())
        self.downlinksCheckBox.setSizePolicy(sizePolicy)
        self.downlinksCheckBox.setText(_fromUtf8(""))
        self.downlinksCheckBox.setChecked(True)
        self.downlinksCheckBox.setObjectName(_fromUtf8("downlinksCheckBox"))
        self.horizontalLayout_3.addWidget(self.downlinksCheckBox)
        self.downlinksLabel = QtGui.QLabel(self.widget)
        self.downlinksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.downlinksLabel.setObjectName(_fromUtf8("downlinksLabel"))
        self.horizontalLayout_3.addWidget(self.downlinksLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.downlinksTreeWidget = QtGui.QTreeWidget(self.widget)
        self.downlinksTreeWidget.setObjectName(_fromUtf8("downlinksTreeWidget"))
        self.downlinksTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_2.addWidget(self.downlinksTreeWidget)
        self.editDownlinksButton = QtGui.QPushButton(self.widget)
        self.editDownlinksButton.setObjectName(_fromUtf8("editDownlinksButton"))
        self.verticalLayout_2.addWidget(self.editDownlinksButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.editTab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(clauseViewWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(clauseViewWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(clauseViewWidget)

    def retranslateUi(self, clauseViewWidget):
        clauseViewWidget.setWindowTitle(QtGui.QApplication.translate("clauseViewWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("clauseViewWidget", "<--", None, QtGui.QApplication.UnicodeUTF8))
        self.returnButton.setText(QtGui.QApplication.translate("clauseViewWidget", "<]", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLabel.setText(QtGui.QApplication.translate("clauseViewWidget", "Documento: Título da Cláusula", None, QtGui.QApplication.UnicodeUTF8))
        self.upButton.setText(QtGui.QApplication.translate("clauseViewWidget", "î", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("clauseViewWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("clauseViewWidget", "-->", None, QtGui.QApplication.UnicodeUTF8))
        self.uplinksLabel.setText(QtGui.QApplication.translate("clauseViewWidget", "Uplinks", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setText(QtGui.QApplication.translate("clauseViewWidget", "Negrito", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setText(QtGui.QApplication.translate("clauseViewWidget", "Itálico", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setText(QtGui.QApplication.translate("clauseViewWidget", "Sublinhado", None, QtGui.QApplication.UnicodeUTF8))
        self.imageButton.setText(QtGui.QApplication.translate("clauseViewWidget", "Imagem", None, QtGui.QApplication.UnicodeUTF8))
        self.downlinksLabel.setText(QtGui.QApplication.translate("clauseViewWidget", "Downlinks", None, QtGui.QApplication.UnicodeUTF8))
        self.editDownlinksButton.setText(QtGui.QApplication.translate("clauseViewWidget", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editTab), QtGui.QApplication.translate("clauseViewWidget", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("clauseViewWidget", "Histórico", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("clauseViewWidget", "Documentos Relacionados", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    clauseViewWidget = QtGui.QWidget()
    ui = Ui_clauseViewWidget()
    ui.setupUi(clauseViewWidget)
    clauseViewWidget.show()
    sys.exit(app.exec_())

