# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectConsolidationWizard.ui'
#
# Created: Thu Jul  4 14:09:11 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ProjectConsolidationWizard(object):
    def setupUi(self, ProjectConsolidationWizard):
        ProjectConsolidationWizard.setObjectName(_fromUtf8("ProjectConsolidationWizard"))
        ProjectConsolidationWizard.resize(603, 527)
        ProjectConsolidationWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        ProjectConsolidationWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.documentsTreeWidget = QtGui.QTreeWidget(self.wizardPage2)
        self.documentsTreeWidget.setObjectName(_fromUtf8("documentsTreeWidget"))
        self.verticalLayout.addWidget(self.documentsTreeWidget)
        ProjectConsolidationWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.typesTreeWidget = QtGui.QTreeWidget(self.wizardPage3)
        self.typesTreeWidget.setObjectName(_fromUtf8("typesTreeWidget"))
        self.verticalLayout_2.addWidget(self.typesTreeWidget)
        ProjectConsolidationWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName(_fromUtf8("wizardPage4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.wizardPage4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.consistencyLabel = QtGui.QLabel(self.wizardPage4)
        self.consistencyLabel.setWordWrap(True)
        self.consistencyLabel.setObjectName(_fromUtf8("consistencyLabel"))
        self.verticalLayout_8.addWidget(self.consistencyLabel)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.yesConsistencyButton = QtGui.QRadioButton(self.wizardPage4)
        self.yesConsistencyButton.setChecked(True)
        self.yesConsistencyButton.setObjectName(_fromUtf8("yesConsistencyButton"))
        self.verticalLayout_7.addWidget(self.yesConsistencyButton)
        self.noConsistencyButton = QtGui.QRadioButton(self.wizardPage4)
        self.noConsistencyButton.setObjectName(_fromUtf8("noConsistencyButton"))
        self.verticalLayout_7.addWidget(self.noConsistencyButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.prefixLabel = QtGui.QLabel(self.wizardPage4)
        self.prefixLabel.setEnabled(False)
        self.prefixLabel.setObjectName(_fromUtf8("prefixLabel"))
        self.verticalLayout_3.addWidget(self.prefixLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.documentPrefixCheckBox = QtGui.QCheckBox(self.wizardPage4)
        self.documentPrefixCheckBox.setEnabled(False)
        self.documentPrefixCheckBox.setChecked(True)
        self.documentPrefixCheckBox.setObjectName(_fromUtf8("documentPrefixCheckBox"))
        self.horizontalLayout.addWidget(self.documentPrefixCheckBox)
        self.typePrefixCheckBox = QtGui.QCheckBox(self.wizardPage4)
        self.typePrefixCheckBox.setEnabled(False)
        self.typePrefixCheckBox.setChecked(True)
        self.typePrefixCheckBox.setObjectName(_fromUtf8("typePrefixCheckBox"))
        self.horizontalLayout.addWidget(self.typePrefixCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.orderLabel = QtGui.QLabel(self.wizardPage4)
        self.orderLabel.setEnabled(False)
        self.orderLabel.setObjectName(_fromUtf8("orderLabel"))
        self.verticalLayout_6.addWidget(self.orderLabel)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.typeOrderButton = QtGui.QRadioButton(self.wizardPage4)
        self.typeOrderButton.setEnabled(False)
        self.typeOrderButton.setChecked(True)
        self.typeOrderButton.setObjectName(_fromUtf8("typeOrderButton"))
        self.verticalLayout_5.addWidget(self.typeOrderButton)
        self.documentOrderButton = QtGui.QRadioButton(self.wizardPage4)
        self.documentOrderButton.setEnabled(False)
        self.documentOrderButton.setObjectName(_fromUtf8("documentOrderButton"))
        self.verticalLayout_5.addWidget(self.documentOrderButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.unifyDocumentsCheckBox = QtGui.QCheckBox(self.wizardPage4)
        self.unifyDocumentsCheckBox.setEnabled(False)
        self.unifyDocumentsCheckBox.setObjectName(_fromUtf8("unifyDocumentsCheckBox"))
        self.verticalLayout_9.addWidget(self.unifyDocumentsCheckBox)
        ProjectConsolidationWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName(_fromUtf8("wizardPage5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.wizardPage5)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.TIMCheckBox = QtGui.QCheckBox(self.wizardPage5)
        self.TIMCheckBox.setObjectName(_fromUtf8("TIMCheckBox"))
        self.verticalLayout_10.addWidget(self.TIMCheckBox)
        self.previousIndexesCheckBox = QtGui.QCheckBox(self.wizardPage5)
        self.previousIndexesCheckBox.setObjectName(_fromUtf8("previousIndexesCheckBox"))
        self.verticalLayout_10.addWidget(self.previousIndexesCheckBox)
        self.newClausesReportCheckBox = QtGui.QCheckBox(self.wizardPage5)
        self.newClausesReportCheckBox.setObjectName(_fromUtf8("newClausesReportCheckBox"))
        self.verticalLayout_10.addWidget(self.newClausesReportCheckBox)
        self.errorsReportCheckBox = QtGui.QCheckBox(self.wizardPage5)
        self.errorsReportCheckBox.setObjectName(_fromUtf8("errorsReportCheckBox"))
        self.verticalLayout_10.addWidget(self.errorsReportCheckBox)
        ProjectConsolidationWizard.addPage(self.wizardPage5)

        self.retranslateUi(ProjectConsolidationWizard)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.prefixLabel.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.documentPrefixCheckBox.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.typePrefixCheckBox.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.orderLabel.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.typeOrderButton.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.documentOrderButton.setEnabled)
        QtCore.QObject.connect(self.noConsistencyButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.unifyDocumentsCheckBox.setEnabled)
        QtCore.QObject.connect(self.typeOrderButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.unifyDocumentsCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ProjectConsolidationWizard)

    def retranslateUi(self, ProjectConsolidationWizard):
        ProjectConsolidationWizard.setWindowTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Consolidação de Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Escolha de documentos", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setSubTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Escolha os documentos que irão fazer parte da consolidação:", None, QtGui.QApplication.UnicodeUTF8))
        self.documentsTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("ProjectConsolidationWizard", "Documentos", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Escolha de Tipos", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setSubTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Escolha quais tipos participarão da consolidação:", None, QtGui.QApplication.UnicodeUTF8))
        self.typesTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("ProjectConsolidationWizard", "Tipos", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Definições de Exibição", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setSubTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Defina como as cláusulas serão nomeadas e organizadas:", None, QtGui.QApplication.UnicodeUTF8))
        self.consistencyLabel.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Manter consistência com consolidações passadas? Caso a consistência seja mantida, cláusulas já consolidadas manterão seus índices. Nesse caso, novas cláusulas terão seus índices mais altos que as cláusulas já consolidadas e a numeração poderá apresentar lacunas. As numerações e índices serão gerados como a consolidação anterior.", None, QtGui.QApplication.UnicodeUTF8))
        self.yesConsistencyButton.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.noConsistencyButton.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Não", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Prefixo:", None, QtGui.QApplication.UnicodeUTF8))
        self.documentPrefixCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Prefixo de documento", None, QtGui.QApplication.UnicodeUTF8))
        self.typePrefixCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Prefixo de tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.orderLabel.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Ordenamento:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeOrderButton.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Ordenar por tipos (tipos de ordem maior primeiro)", None, QtGui.QApplication.UnicodeUTF8))
        self.documentOrderButton.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Como ordenado nos documentos", None, QtGui.QApplication.UnicodeUTF8))
        self.unifyDocumentsCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Juntar todos documentos selecionados em um único", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage5.setTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Anexos", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage5.setSubTitle(QtGui.QApplication.translate("ProjectConsolidationWizard", "Escolha quais relatórios serão anexados à consolidação:", None, QtGui.QApplication.UnicodeUTF8))
        self.TIMCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Definições do Modelo de Informações de Rastreabiliade (TIM)", None, QtGui.QApplication.UnicodeUTF8))
        self.previousIndexesCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Conversões de índices consolidades anteriormente", None, QtGui.QApplication.UnicodeUTF8))
        self.newClausesReportCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Lista de novas cláusulas consolidadas", None, QtGui.QApplication.UnicodeUTF8))
        self.errorsReportCheckBox.setText(QtGui.QApplication.translate("ProjectConsolidationWizard", "Relatório de erros encontrados", None, QtGui.QApplication.UnicodeUTF8))

